name: Pull Request CI
on:
  pull_request:
permissions:
  contents: read
jobs:
  release:
    name: Pull Request
    runs-on: ubuntu-latest
    concurrency:
      group: pr-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          show-progress: 'false'
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
          cache: 'maven'
      - name: PR Conventional Commit Validation
        uses: dev-build-deploy/commit-me@v0
        with:
          update-labels: false  # OPTIONAL; do not update the Pull Request labels based on the Conventional Commits information.
          include-commits: false  # OPTIONAL; enforces the exclusion of commits associated with your Pull Request
      - name: Test and Analyse
        run: ./mvnw clean verify --show-progress=false